app:
  name: "godest"
  port: ":9090"
  mode: "debug"

database:
  driver: "postgres"
  # source: "godest.db"
  host: "127.0.0.1"
  port: "5432"
  username: "postgres"
  password: ""
  database: "godest"
  sslmode: "disable"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

jwt:
  secret: ""
  expire: 24
