app:
  name: "godest"
  port: ":9090"
  mode: "debug"

database:
  driver: "sqlite"
  source: "godest.db"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

jwt:
  secret: "your-secret-key-should-be-complex"
  expire: 24
