// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"go_pro/internal/handler"
	"go_pro/internal/repository"
	"go_pro/internal/service"
	"go_pro/pkg/cache"
	"go_pro/pkg/utils"
	"go_pro/router"
)

// Injectors from wire.go:

func InitApp() (*gin.Engine, error) {
	iUserRepository := repository.NewUserRepository()
	redisClient := cache.NewRedisClient()
	jwtUtil := utils.NewJWTUtil()
	passwordUtil := utils.NewPasswordUtil()
	userService := service.NewUserService(iUserRepository, redisClient, jwtUtil, passwordUtil)
	userHandler := handler.NewUserHandler(userService)
	engine := router.Init(userHandler)
	return engine, nil
}
