// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"godest/internal/platform/http/router"
	"godest/internal/user/api"
	"godest/internal/user/app"
	"godest/internal/user/infra/repository"
	"godest/pkg/cache"
	"godest/pkg/utils"
)

// Injectors from wire.go:

func InitApp() (*gin.Engine, error) {
	domainRepository := repository.NewUserRepository()
	redisClient := cache.NewRedisClient()
	jwtUtil := utils.NewJWTUtil()
	passwordUtil := utils.NewPasswordUtil()
	userService := app.NewUserService(domainRepository, redisClient, jwtUtil, passwordUtil)
	userHandler := api.NewUserHandler(userService)
	engine := router.Init(userHandler, jwtUtil)
	return engine, nil
}
